#Workshop 1


#Problem 1


In [43]:
#1.1
np.empty((2,2))

array([[4.71092587e-315, 0.00000000e+000],
       [9.88131292e-324,             nan]])

In [44]:
#1.2
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [45]:
#1.3
np.full((3,4), 7 , dtype =int)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [46]:
#1.4
a =np.array([[1,2,3],
            [4,5,6]], dtype=float)
np.zeros_like(a)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
#1.5
a =np.array([[1,2,3],
            [4,5,6]], dtype=float)
np.ones_like(a)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [48]:
#1.6
new_list=[1,2,3,4]

np.array(new_list)

array([1, 2, 3, 4])

#Problem 2


In [49]:
#2.1
np.arange(10,49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [50]:
#2.2

In [51]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [52]:
#2.3
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
#2.4
a = np.random.random(30)
a.mean()

np.float64(0.36772995498558403)

In [54]:
#2.5
np.random.randint(40, size=(10,10))
a.max()


np.float64(0.9989861020514264)

In [55]:
a.min()

np.float64(0.020586188590708487)

In [56]:
#2.6
a = np.zeros(10)
a[4]=1
a


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [57]:
#2.7
a = np.array([1,2,0,0,4,0])
np.flip(a)


array([0, 4, 0, 0, 2, 1])

In [58]:
#2.8

a =np.ones((6,8), dtype=int)

a[1:-1, 1:-1] =0
a

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [59]:
#2.9
board = np.zeros((8,8), dtype=int)
board[::2, ::2] =1
board[1::2, 1::2] = 1

board


array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#Problem 3


In [60]:
x= np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

print("Original arrays:")
print("x =\n", x)
print("y =\n", y)
print("v =", v)
print("w =", w)
print()

#1
print("1. Addition:")
print("x + y =\n", x + y)
print()

#2
print("2. Subtraction:")
print("x - y =\n", x - y)
print()

#3
print("3. Multiplication with integers:")
print("x * 3 =\n", x * 3)
print("y * 2 =\n", y * 2)
print()

#4.
print("4. Square of each element:")
print("x² =\n",x**2)
print("y² =\n",y**2)
print("v² =", v**2)
print()

#5.
print("5. Dot products:")
print("v · w =", np.dot(v, w))
print("x · v =", np.dot(x, v))
print("x · y =\n", np.dot(x, y))
print()

#6.
print("6. Concatenation:")
xyrow = np.concatenate((x, y), axis=0)
print("x and y along rows:\n", xyrow)

#Concatenate v and w along column
vwcol = np.column_stack((v, w))
print("v and w along columns:\n", vwcol)



Original arrays:
x =
 [[1 2]
 [3 5]]
y =
 [[5 6]
 [7 8]]
v = [ 9 10]
w = [11 12]

1. Addition:
x + y =
 [[ 6  8]
 [10 13]]

2. Subtraction:
x - y =
 [[-4 -4]
 [-4 -3]]

3. Multiplication with integers:
x * 3 =
 [[ 3  6]
 [ 9 15]]
y * 2 =
 [[10 12]
 [14 16]]

4. Square of each element:
x² =
 [[ 1  4]
 [ 9 25]]
y² =
 [[25 36]
 [49 64]]
v² = [ 81 100]

5. Dot products:
v · w = 219
x · v = [29 77]
x · y =
 [[19 22]
 [50 58]]

6. Concatenation:
x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
v and w along columns:
 [[ 9 11]
 [10 12]]


In [61]:
np.concatenate((x,v))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

we get error because x is 2d array and v is 1 d array. the concatenacion requires both arrays to have the same number of dimensions.


#Problem 4

In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])


#1.
A_inv = np.linalg.inv(A)
print("A inverse =\n", A_inv)

eye = np.dot(A, A_inv)
print("A.A⁻¹ =\n", eye)

In [ ]:
#2 Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB =\n", AB)
print("BA =\n", BA)

are_equal = np.array_equal(AB, BA)
print("Are AB and BA equal?", are_equal)

In [ ]:
#3
AB=np.dot(A,B)
ABtransp = AB.T
print("AB transpose", ABtransp)

Btransp = B.T
Atransp = A.T
BT_AT = np.dot(Btransp, Atransp)
print("B transpose . A Transpose =\n", BT_AT)

equal = np.array_equal(ABtransp, BT_AT)
print("Are (AB)Transpose and BTranspose.ATranspose equal?", equal)